# Generated by Django 2.2.7 on 2019-11-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('vendor', models.CharField(max_length=200)),
                ('mrp', models.FloatField(max_length=10)),
                ('batch_num', models.IntegerField()),
                ('batch_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
        ),
    ]
