# Generated by Django 2.2.7 on 2019-11-27 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='author',
        ),
    ]
