# Generated by Django 2.2.7 on 2019-11-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_inventory_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='batch_date',
            field=models.DateField(null=True),
        ),
    ]
