# Generated by Django 2.2.7 on 2019-11-27 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventory_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
