# Generated by Django 2.2.7 on 2019-12-01 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0008_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryApproval',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('vendor', models.CharField(max_length=200)),
                ('mrp', models.FloatField(max_length=10)),
                ('batch_num', models.IntegerField()),
                ('batch_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('status', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
