# Generated by Django 2.2.7 on 2019-12-02 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_inventoryapproval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='status',
        ),
    ]
