# Generated by Django 2.2.7 on 2019-12-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20191202_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryapproval',
            name='action',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
